name: Create a new pre-release build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: "Version (\"aX\" / \"a24\")"
        default: "a"
        required: true
        type: string

jobs:
  linux-builder:
    name: "Build - Linux"
    uses: ./.github/workflows/build-dev-linux.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}

  windows-builder:
    name: "Build - Windows"
    uses: ./.github/workflows/build-dev-windows.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}

  mac-builder:
    name: "Build - MacOS"
    uses: ./.github/workflows/build-dev-mac.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}